const products = [
  {
    id: "1",
    name: "A",
    price: 500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 10,
    description: "Descripcion de A",
  },
  {
    id: "2",
    name: "B",
    price: 1000,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 15,
    description: "Descripcion de B",
  },
  {
    id: "3",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "4",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "5",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "6",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "7",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "8",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "9",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "10",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "11",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "12",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "13",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "14",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "15",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "16",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "17",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "18",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "19",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
  {
    id: "20",
    name: "C",
    price: 1500,
    category: "Categoría A",
    img: "images/imagenGenerica.jpg",
    stock: 20,
    description: "Descripcion de C",
  },
];

export const getProducts = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(products);
    }, 2000);
  });
};
